/**
 * Parity test for the in-process citation converter (src/convertCitations.ts),
 * which must behave exactly like scripts/convert-citations.mjs. The expected
 * outputs below were generated by running that script on the same inputs.
 */
import { convertCitationsInText } from '../convertCitations';

describe('convertCitationsInText', () => {
  const cases: [string, string][] = [
    ['[[@smith2020]]', '[@smith2020]'],
    ['[[@key|@]]', '[@key]'],
    ['[[@smith2020|see @, p. 6]]', '[see @smith2020, p. 6]'],
    ['[[@key|-@, p. 6]]', '[-@key, p. 6]'],
    ["[[@smith2020|Smith's work]]", "Smith's work [@smith2020]"],
    ['[ [[@a]]; [[@b]] ]', '[@a; @b]'],
    ['[ see also [[@a]]; [[@b]] ]', '[@a; @b]'],
    ['[ [[@a]]; [@b, p. 5] ]', '[@a; @b, p. 5]'],
    ['[[@key|@ -]]', '@key'],
    ['[[@key|see @ -]]', 'see @key'],
    ['[[@key|-@]]', '[-@key]'],
    ['[ [[@a|@ -]]; [[@b]] ]', '@a [@b]'],
    ['[ [[@a]]; [[@b|@ -]] ]', '[@a; @b]'],
    ['[[@a|@, vol. I, p. 113]]', '[@a, 1:113]'],
    ['plain [[note name]] link', 'plain [[note name]] link'],
  ];

  it.each(cases)('%s → %s', (input, expected) => {
    expect(convertCitationsInText(input)).toBe(expected);
  });

  it('converts each line independently and preserves line structure', () => {
    const input = 'Intro [[@a]].\n\n- item [[@b|@, p. 2]]\n\nplain line';
    expect(convertCitationsInText(input)).toBe(
      'Intro [@a].\n\n- item [@b, p. 2]\n\nplain line'
    );
  });
});
