import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Resolve "src/..." imports as if the project root contains a "src" directory.
// Mirrors TypeScript "paths": { "src/*": ["./src/*"] } without tsconfig.
const srcAliasPlugin = {
	name: "src-alias",
	setup(build) {
		build.onResolve({ filter: /^src\// }, (args) => {
			const relative = args.path.slice(4); // strip "src/"
			const base = path.resolve(__dirname, "src", relative);

			// Probe candidate paths in priority order.
			const candidates = [
				base,            // exact (if someone wrote the extension)
				base + ".ts",
				base + ".tsx",
				base + ".js",
				path.join(base, "index.ts"),
				path.join(base, "index.tsx"),
				path.join(base, "index.js"),
			];

			for (const candidate of candidates) {
				if (fs.existsSync(candidate)) {
					return { path: candidate };
				}
			}

			// Couldn't resolve — return the bare path so esbuild emits a
			// useful "could not read file" error pointing at the right location.
			return { path: base + ".ts" };
		});
	},
};

const options = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [srcAliasPlugin],
};

if (prod) {
	await esbuild.build(options);
	process.exit(0);
} else {
	await esbuild.build({ ...options, watch: true });
}
