// Common CSL citation styles. The `value` is the style's canonical ID used by
// citeproc-js / Pandoc; the `label` is the human-readable display name.
// A curated list of the most widely used academic styles is included here.
// Users can point to a custom .csl file in the settings to use any style.

export const cslListRaw: { value: string; label: string }[] = [
  { value: 'apa', label: 'American Psychological Association (APA) 7th edition' },
  { value: 'apa-6th-edition', label: 'American Psychological Association (APA) 6th edition' },
  { value: 'chicago-author-date', label: 'Chicago Manual of Style (author-date)' },
  { value: 'chicago-note-bibliography', label: 'Chicago Manual of Style (notes and bibliography)' },
  { value: 'chicago-fullnote-bibliography', label: 'Chicago Manual of Style (full note, bibliography)' },
  { value: 'mla', label: 'Modern Language Association (MLA) 9th edition' },
  { value: 'mla-8', label: 'Modern Language Association (MLA) 8th edition' },
  { value: 'harvard-cite-them-right', label: 'Harvard (Cite Them Right)' },
  { value: 'vancouver', label: 'Vancouver' },
  { value: 'nature', label: 'Nature' },
  { value: 'science', label: 'Science' },
  { value: 'cell', label: 'Cell' },
  { value: 'ieee', label: 'IEEE' },
  { value: 'acm-sig-proceedings', label: 'ACM SIG Proceedings' },
  { value: 'acm-sigchi-proceedings', label: 'ACM SIGCHI Proceedings' },
  { value: 'american-medical-association', label: 'American Medical Association (AMA)' },
  { value: 'american-chemical-society', label: 'American Chemical Society (ACS)' },
  { value: 'american-physics-society', label: 'American Physics Society (APS)' },
  { value: 'american-sociological-association', label: 'American Sociological Association (ASA)' },
  { value: 'annual-reviews', label: 'Annual Reviews' },
  { value: 'biomed-central', label: 'BioMed Central (BMC)' },
  { value: 'bmj', label: 'BMJ' },
  { value: 'british-journal-of-psychiatry', label: 'British Journal of Psychiatry' },
  { value: 'cambridge-university-press', label: 'Cambridge University Press' },
  { value: 'council-of-science-editors-author-date', label: 'Council of Science Editors (author-date)' },
  { value: 'council-of-science-editors', label: 'Council of Science Editors (citation-sequence)' },
  { value: 'current-biology', label: 'Current Biology' },
  { value: 'developmental-cell', label: 'Developmental Cell' },
  { value: 'ecology', label: 'Ecology' },
  { value: 'elsevier-harvard', label: 'Elsevier (Harvard)' },
  { value: 'elsevier-with-titles', label: 'Elsevier (with titles)' },
  { value: 'elsevier-vancouver', label: 'Elsevier (Vancouver)' },
  { value: 'frontiers-in-psychology', label: 'Frontiers in Psychology' },
  { value: 'harvard-anglia-ruskin-university', label: 'Harvard (Anglia Ruskin University)' },
  { value: 'jama', label: 'JAMA (Journal of the American Medical Association)' },
  { value: 'journal-of-the-american-chemical-society', label: 'Journal of the American Chemical Society' },
  { value: 'journal-of-political-philosophy', label: 'Journal of Political Philosophy' },
  { value: 'lancet', label: 'The Lancet' },
  { value: 'new-england-journal-of-medicine', label: 'New England Journal of Medicine' },
  { value: 'oscola', label: 'Oxford University Standard for Citation of Legal Authorities (OSCOLA)' },
  { value: 'oxford-university-press-humsoc', label: 'Oxford University Press (humanities and social sciences)' },
  { value: 'oxford-university-press-scimed', label: 'Oxford University Press (science and medicine)' },
  { value: 'plos', label: 'Public Library of Science (PLOS)' },
  { value: 'political-analysis', label: 'Political Analysis' },
  { value: 'proceedings-of-the-national-academy-of-sciences', label: 'Proceedings of the National Academy of Sciences (PNAS)' },
  { value: 'royal-society-of-chemistry', label: 'Royal Society of Chemistry' },
  { value: 'sage-harvard', label: 'SAGE (Harvard)' },
  { value: 'sage-vancouver', label: 'SAGE (Vancouver)' },
  { value: 'springer-basic-author-date', label: 'Springer (basic author-date)' },
  { value: 'springer-humanities-author-date', label: 'Springer (humanities author-date)' },
  { value: 'springer-lecture-notes-in-computer-science', label: 'Springer Lecture Notes in Computer Science' },
  { value: 'taylor-and-francis-national-library-of-medicine', label: 'Taylor & Francis (NLM/Vancouver)' },
  { value: 'taylor-and-francis-chicago-author-date', label: 'Taylor & Francis (Chicago author-date)' },
  { value: 'turabian-author-date', label: 'Turabian (author-date)' },
  { value: 'turabian-fullnote-bibliography', label: 'Turabian (full note)' },
  { value: 'wiley-communications-in-mathematical-physics', label: 'Wiley (Communications in Math Physics)' },
];
