// CSL locale language list. The `value` is the BCP 47 language tag used in
// the CSL locale file names (e.g. "en-US" → locales-en-US.xml); the `label`
// is the display name shown in the settings dropdown.

export const langListRaw: { value: string; label: string }[] = [
  { value: 'af-ZA', label: 'Afrikaans' },
  { value: 'ar', label: 'Arabic' },
  { value: 'bg-BG', label: 'Bulgarian' },
  { value: 'ca-AD', label: 'Catalan' },
  { value: 'cs-CZ', label: 'Czech' },
  { value: 'cy-GB', label: 'Welsh' },
  { value: 'da-DK', label: 'Danish' },
  { value: 'de-AT', label: 'German (Austria)' },
  { value: 'de-CH', label: 'German (Switzerland)' },
  { value: 'de-DE', label: 'German (Germany)' },
  { value: 'el-GR', label: 'Greek' },
  { value: 'en-GB', label: 'English (UK)' },
  { value: 'en-US', label: 'English (US)' },
  { value: 'es-CL', label: 'Spanish (Chile)' },
  { value: 'es-ES', label: 'Spanish (Spain)' },
  { value: 'es-MX', label: 'Spanish (Mexico)' },
  { value: 'et-EE', label: 'Estonian' },
  { value: 'eu', label: 'Basque' },
  { value: 'fa-IR', label: 'Persian' },
  { value: 'fi-FI', label: 'Finnish' },
  { value: 'fr-CA', label: 'French (Canada)' },
  { value: 'fr-FR', label: 'French (France)' },
  { value: 'gl-ES', label: 'Galician' },
  { value: 'he-IL', label: 'Hebrew' },
  { value: 'hr-HR', label: 'Croatian' },
  { value: 'hu-HU', label: 'Hungarian' },
  { value: 'id-ID', label: 'Indonesian' },
  { value: 'is-IS', label: 'Icelandic' },
  { value: 'it-IT', label: 'Italian' },
  { value: 'ja-JP', label: 'Japanese' },
  { value: 'km-KH', label: 'Khmer' },
  { value: 'ko-KR', label: 'Korean' },
  { value: 'la', label: 'Latin' },
  { value: 'lt-LT', label: 'Lithuanian' },
  { value: 'lv-LV', label: 'Latvian' },
  { value: 'mn-MN', label: 'Mongolian' },
  { value: 'nb-NO', label: 'Norwegian (Bokmål)' },
  { value: 'nl-NL', label: 'Dutch' },
  { value: 'nn-NO', label: 'Norwegian (Nynorsk)' },
  { value: 'pl-PL', label: 'Polish' },
  { value: 'pt-BR', label: 'Portuguese (Brazil)' },
  { value: 'pt-PT', label: 'Portuguese (Portugal)' },
  { value: 'ro-RO', label: 'Romanian' },
  { value: 'ru-RU', label: 'Russian' },
  { value: 'sk-SK', label: 'Slovak' },
  { value: 'sl-SI', label: 'Slovenian' },
  { value: 'sr-RS', label: 'Serbian' },
  { value: 'sv-SE', label: 'Swedish' },
  { value: 'th-TH', label: 'Thai' },
  { value: 'tr-TR', label: 'Turkish' },
  { value: 'uk-UA', label: 'Ukrainian' },
  { value: 'ur', label: 'Urdu' },
  { value: 'vi-VN', label: 'Vietnamese' },
  { value: 'zh-CN', label: 'Chinese (Simplified)' },
  { value: 'zh-TW', label: 'Chinese (Traditional)' },
];
